services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    command: sleep infinity
    volumes:
      - ..:/workspaces/folio:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - dev_pip_cache:/root/.cache/pip
      - dev_npm_cache:/root/.npm
    environment:
      - APP_DATA_DIR=/root/.local/share/folio
      - APP_TMP_DIR=/root/.local/share/folio/tmp
      - APP_LOG_DIR=/root/.local/share/folio/logs
    working_dir: /workspaces/folio

volumes:
  dev_pip_cache:
  dev_npm_cache: